project_id = "viewclpgpnhptpjmkqxh"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.save-user-role]
verify_jwt = false

[functions.generate-admin-qr]
verify_jwt = false

[functions.verify-admin-qr]
verify_jwt = false

[functions.check-admin-session]
verify_jwt = false

[functions.generate-studio-qr]
verify_jwt = false

[functions.verify-studio-qr]
verify_jwt = false

[functions.check-studio-session]
verify_jwt = false
